language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4

jobs:
  include:
  - php: 7.4
    env: KEY=VALUE
  allow_failures:
  - php: 7.4
    env: KEY=VALUE
    
    jobs:
  fast_finish: true
  
   deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: moodle_branch_1