language: php
php:
- 5.6
- 7.0
jobs:
  include:
  - php: 7.0
    env: KEY=VALUE
  allow_failures:
  - php: 7.0
    env: KEY=VALUE
    
    jobs:
  fast_finish: true
  
   deploy:
    provider: pages
    skip-cleanup: true
    github-token: $travismoodleci
    on:
      branch: moodle_branch_1