# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:

  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 7.2
    - php: 7.4
  fast_finish: true

# Customize when the notification emails are sent.
    
    deploy:
    provider: pages
    skip-cleanup: true
    github-token: $travismoodleci
    on:
      branch: moodle_branch_1

notifications:
  email:
    recipients:
      - balajis@yakshnatechnologies.in
      - other@example.com
    on_success: never # default: change
    on_failure: always # default: always